### ISSUE TITLE
แต่ละ task ควรมีการบอกว่าทำอะไร ไม่ใช่เขียนสั้น ๆ

### ISSUE THREAD

**Issue by up1** [BurnRadish/SW-Development_Group6_Project#4]
แต่ละ task ควรมีการบอกว่าทำอะไร ไม่ใช่เขียนสั้น ๆ

**Comment by BurnRadish** [comment]
ทำการเพิ่มรายละเอียดแต่ task ลงในคำอธิบายการ์ดใน trello
